# Generated by Django 5.2.4 on 2025-07-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ref_by',
        ),
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReferralEarning',
        ),
        migrations.DeleteModel(
            name='WithdrawRequest',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
