# Generated by Django 5.2.4 on 2025-07-23 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('ref_by', models.BigIntegerField(blank=True, null=True)),
                ('joined_at', models.TextField(blank=True, null=True)),
                ('bonus_balance', models.FloatField(default=0)),
                ('total_bonus', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.BigIntegerField()),
                ('amount', models.FloatField()),
                ('level', models.IntegerField()),
                ('date', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='bot.users')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdt', models.FloatField(default=0)),
                ('trx', models.FloatField(default=0)),
                ('bdt', models.FloatField(default=0)),
                ('pkr', models.FloatField(default=0)),
                ('idr', models.FloatField(default=0)),
                ('date', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.users')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.TextField()),
                ('status', models.TextField()),
                ('created_at', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.users')),
            ],
        ),
    ]
