# Generated by Django 5.2.4 on 2025-07-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_withdrawrequests_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='team_reset_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
