# Generated by Django 5.2.4 on 2025-07-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_users_team_reset_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
